tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/services"
tap "git-chglog/git-chglog"

cask_args appdir: "/Applications"

brew "ack"
brew "ansible"
brew "asdf"
brew "aspell"
brew "autoconf"
brew "automake"
brew "awscli"
brew "bash"
brew "bash-completion@2"
brew "cask"
brew "certbot"
brew "cloc"
brew "coreutils"
brew "curl"
brew "exercism"
brew "git"
brew "git-chglog"
brew "git-crypt"
brew "git-lfs"
brew "git-open"
brew "git-quick-stats"
brew "gnupg"
brew "gnuplot"
brew "gnutls"
brew "graphviz"
brew "gzip"
brew "hopenpgp-tools"
brew "htop"
brew "httpie"
brew "ipcalc"
brew "iperf"
brew "jq"
brew "mas"
brew "mtr"
brew "ncdu"
brew "neofetch"
brew "neovim"
brew "nmap"
brew "pandoc"
brew "pinentry-mac"
brew "pstree"
brew "pv"
brew "ranger"
brew "readline"
brew "shellcheck"
brew "sox"
brew "speedtest-cli"
brew "sqlite"
brew "ssh-copy-id"
brew "telnet"
brew "terminal-notifier"
brew "testssl"
brew "tmux"
brew "tree"
brew "vnstat"
brew "watch"
brew "wget"
brew "ykman"
brew "youtube-dl"
brew "yubikey-personalization"
brew "zlib"
cask "anki"
cask "authy"
cask "bartender"
cask "burp-suite"
cask "discord"
cask "firefox"
cask "flux"
cask "font-fira-code-nerd-font"
cask "iterm2"
cask "little-snitch"
cask "microsoft-edge"
cask "rectangle"
cask "tunnelblick"
cask "utc-menu-clock"
cask "visual-studio-code"
mas "1Password 7", id: 1333542190
mas "Amphetamine", id: 937984704
mas "FoldingText", id: 540003654
mas "Gifox", id: 1461845568
mas "Kindle", id: 405399194
mas "Marked 2", id: 890031187
mas "Micro Snitch", id: 972028355
mas "Noizio", id: 928871589
mas "Xcode", id: 497799835
mas "iA Writer", id: 775737590
mas "Tailscale", id: 1475387142
mas "Reeder", id: 1449412482
mas "Tot", id: 1491071483
mas "Tailscale", id: 1475387142
