env:
  TERM: xterm-256color

# windows
window:
    decorations: buttonless
    startup_mode: Maximized
    padding:
      x: 2
      y: 2
    dynamic_padding: false

# Visual Bell
bell:
  animation: EaseOutExpo
  duration: 0

# Colors (Gruvbox light)
colors:
  # Default colors
  primary:
    # hard contrast: background = '#f9f5d7'
    background: '#fbf1c7'
    # soft contrast: background = '#f2e5bc'
    foreground: '#3c3836'

  # Normal colors
  normal:
    black:   '#fbf1c7'
    red:     '#cc241d'
    green:   '#98971a'
    yellow:  '#d79921'
    blue:    '#458588'
    magenta: '#b16286'
    cyan:    '#689d6a'
    white:   '#7c6f64'

  # Bright colors
  bright:
    black:   '#928374'
    red:     '#9d0006'
    green:   '#79740e'
    yellow:  '#b57614'
    blue:    '#076678'
    magenta: '#8f3f71'
    cyan:    '#427b58'
    white:   '#3c3836'  

font:
  normal:
    family: FiraCode Nerd Font Mono
    style: Regular
  bold:
    family: FiraCode Nerd Font Mono
    style: Bold
  italic:
    family: FiraCode Nerd Font Mono
    style: Italic
  size: 18

mouse:
    hide_when_typing: true

cursor:
    style: Block
    unfocused_hollow: false

url:
  launcher: open

