
[aws]
displayed_items = "all"

[directory]
truncation_length = 2

[hostname]
ssh_only = true
prefix = "⟪"
suffix = "⟫"
disabled = false

[username]
style_user = "bold dimmed blue"
show_always = false
